parameters:
  babymarkt_ext_cron.report.database.driver: pdo_sqlite

doctrine:
  dbal:
    connections:
      babymarkt_ext_cron:
        driver: %babymarkt_ext_cron.report.database.driver%
        user: %babymarkt_ext_cron.report.database.user%
        password: %babymarkt_ext_cron.report.database.password%
        path: %babymarkt_ext_cron.report.database.path%
  orm:
    entity_managers:
      babymarkt_ext_cron:
        connection: babymarkt_ext_cron
        mappings:
          BabymarktExtCronBundle: ~