services:
  # This listener should only be registered if DoctrineBundle is installed.
  babymarkt_ext_cron.listener.executionreport:
    class: BabymarktExt\CronBundle\Service\Listener\ExecutionReportListener
    arguments:
      - %babymarkt_ext_cron.definitions%
      - @babymarkt_ext_cron.service.executionreporter
    tags:
      - {name: kernel.event_listener, event: console.command, method: onCronStart}
      - {name: kernel.event_listener, event: console.terminate, method: onCronFinished}
      - {name: kernel.event_listener, event: console.exception, method: onCronFailed}

  babymarkt_ext_cron.service.executionreporter:
      class: BabymarktExt\CronBundle\Service\CronReport
      arguments:
        - @doctrine.orm.babymarkt_ext_cron_entity_manager
        - %kernel.environment%
        - %babymarkt_ext_cron.definitions%